services:
  nginx:
    image: nginx:latest
    container_name: itaxcix-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html/public
      - ./certs:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - ws
    networks:
      - app-network

  php:
    build: .
    container_name: itaxcix-php
    volumes:
      - uploads_data:/var/www/html/uploads
      - ./:/var/www/html
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_DATABASE}
      DB_USER: ${DB_USERNAME}
      DB_PASS: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    networks:
      - app-network

  postgres:
    image: postgres:14
    container_name: itaxcix-postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  ws:
    build:
      context: .
      dockerfile: Dockerfile.websocket
    container_name: itaxcix-ws
    volumes:
      - ./:/var/www/html
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: itaxcix-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  data:
  redis_data:
  vendor_data:
  uploads_data:

networks:
  app-network:
    driver: bridge