services:
  nginx:
    image: nginx:latest
    container_name: itaxcix-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./certs:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    build: .
    container_name: itaxcix-php
    volumes:
      - ./:/var/www/html
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_DATABASE}
      DB_USER: ${DB_USERNAME}
      DB_PASS: ${DB_PASSWORD}
    networks:
      - app-network

  postgres:
    image: postgres:14
    container_name: itaxcix-postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  ws:
    image: php:8.2-cli
    container_name: itaxcix-ws
    volumes:
      - ./:/var/www/html
      - ./logs:/var/log/php
    command: php /var/www/html/ws/ws-server.php
    environment:
      WS_HOST: ${WS_HOST}
      WS_PORT: ${WS_PORT}
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  data:

networks:
  app-network:
    driver: bridge